
image:
- Visual Studio 2019
- Ubuntu
before_build:
  # Display .NET Core version
  - dotnet --list-sdks
  - dotnet --version
  # Restore deps
  - dotnet tool restore
  - dotnet restore
build_script:
  - dotnet build
before_test:
  - bash scripts/restore.sh
test_script:
  - dotnet test tests/LSP.Tests
  - dotnet test tests/ProjectCracker.Tests
  - dotnet test tests/FSharpLanguageServer.Tests
