name: testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            5.0.x
            3.1.x
      - uses: actions/cache@v2
        with:
          path: ./paket
          key: ${{ runner.os }}-${{ hashFiles('**/paket.lock','**/paket.dependencies') }}
      - run: bash ./scripts/paketActions.sh  
      - name: Restore dependencies
        run: dotnet tool restore
      - name: paket setup
        run: dotnet paket install
      - name: Restore
        run: bash ./scripts/restore.sh
      - name: Test
        run: dotnet test --verbosity normal ./tests/Expecto/
